sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${SERVER_IP}
    port: 3306
    database: sky_take_out
    username: root
    password: Aa114514
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: pet-backer
  redis:
    host: ${SERVER_IP}
    port: 6379
    password: Aa114514
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_APP_SECRET}
    mchid: ${sky.wechat.mchid}
    mch-serial-no: ${sky.wechat.mch-serial-no}
    private-key-file-path: ${sky.wechat.private-key-file-path}
    api-v3-key: ${sky.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${sky.wechat.we-chat-pay-cert-file-path}
    notify-url: ${sky.wechat.notify-url}
    refund-notify-url: ${sky.wechat.refund-notify-url}